strict: true

# Project information
site_name: "Pulse documentation"
site_url: https://docs.pulse.codacy.com/

repo_url: https://app.pulse.codacy.com/
repo_name: Back to the Pulse app

# Configuration
theme:
  name: "material"
  palette:
    scheme: "slate"
    primary: "teal"
    accent: "teal"
  font:
    text: Inter
  logo: "assets/pulse-logo.png"
  features:
    # Disabled to allow Segment to track all page load events
    # https://codacy.atlassian.net/browse/PUL-1228
    # - navigation.instant
    - toc.integrate
  custom_dir: overrides
  icon:
    repo: fontawesome/regular/circle-right

extra:
  analytics:
    provider: segment
    property: "8vbB5QvZbwQqMTCWkaiY9Tx2zQ2EU5AF"

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.striphtml:
      strip_comments: true
  - toc:
      permalink: true

# Plugins
plugins:
    - search
    - meta-descriptions:
          export_csv: true

nav:
  - index.md
  - "Calculated metrics":
    - metrics/accelerate.md
    - metrics/accelerate-changes.md
    - metrics/accelerate-wip.md
    - metrics/lead-cycle-time.md
  - "One-click integrations":
    - one-click-integrations/github-integration.md
    - one-click-integrations/bitbucket-integration.md
    - one-click-integrations/pagerduty-integration.md
    - one-click-integrations/jira-integration.md
  - "Pulse CLI":
    - cli/cli.md
    - cli/examples.md
  - "Ingestion API docs ↗": https://ingestion.pulse.codacy.com/v1/api-docs
