strict: true

# Project information
site_name: "Pulse documentation"
site_url: https://docs.pulse.codacy.com/

# Configuration
theme:
  name: "material"
  palette:
    scheme: "slate"
    primary: "teal"
    accent: "teal"
  # feature:
  #   tabs: true
  logo: "assets/pulse-logo.png"

google_analytics: ["UA-180967824-1", "pulse.codacy.com"]

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.striphtml:
      strip_comments: true
  - toc:
      permalink: true
