strict: true

# Project information
site_name: "Pulse documentation"
site_url: https://docs.pulse.codacy.com/

repo_url: https://app.pulse.codacy.com/
repo_name: Back to the Pulse app

# Configuration
theme:
  name: "material"
  palette:
    scheme: "slate"
    primary: "teal"
    accent: "teal"
  logo: "assets/pulse-logo.png"
  features:
    - navigation.instant
    - toc.integrate
  custom_dir: overrides
  icon:
    repo: fontawesome/regular/arrow-alt-circle-right

google_analytics: ["G-E31MPDGETR", "docs.pulse.codacy.com"]

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.striphtml:
      strip_comments: true
  - toc:
      permalink: true

# Plugins
plugins:
    - search
    - meta-descriptions

nav:
  - index.md
  - "Calculated metrics":
    - metrics/accelerate.md
    - metrics/lead-time-reviews.md
    - metrics/work-in-progress.md
  - one-click-integrations.md
  - "Pulse CLI":
    - cli/installing-the-pulse-cli.md
    - cli/pushing-data-to-pulse.md
    - cli/examples.md
