strict: true

# Project information
site_name: "Pulse documentation"
site_url: https://docs.pulse.codacy.com/

repo_url: https://app.pulse.codacy.com/
repo_name: Back to the Pulse app

# Configuration
theme:
  name: "material"
  palette:
    scheme: "slate"
    primary: "teal"
    accent: "teal"
  logo: "assets/pulse-logo.png"
  features:
    - navigation.instant
    - toc.integrate
  custom_dir: overrides
  icon:
    repo: fontawesome/regular/arrow-alt-circle-right

extra:
  analytics:
    provider: google
    property: G-E31MPDGETR

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.striphtml:
      strip_comments: true
  - toc:
      permalink: true

# Plugins
plugins:
    - search
    - meta-descriptions:
          export_csv: true

nav:
  - index.md
  - "One-click integrations":
    - one-click-integrations/github-integration.md
    - one-click-integrations/pagerduty-integration.md
    - one-click-integrations/jira-integration.md
  - "Pulse CLI":
    - cli/cli.md
    - cli/examples.md
  - "Pulse Ingestion API": https://ingestion.pulse.codacy.com/v1/api-docs
  - "Calculated metrics":
    - metrics/accelerate.md
    - metrics/lead-time-reviews.md
    - metrics/work-in-progress.md
