name: Scheduled jobs

on:
  schedule:
   - cron: "15 5 * * 1"

jobs:
  check-broken-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for broken links
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          args: --verbose ./docs/**/*.md
          jobSummary: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Broken link report
          content-filepath: ./lychee/out.md
          labels: report, automated issue

  compress-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compress images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true

      - name: Create pull request
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v5
        with:
          title: "clean: Compress images"
          branch-suffix: timestamp
          commit-message: "clean: Compress images"
          body: ${{ steps.calibre.outputs.markdown }}
