name: Vale

on:
  pull_request

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: false

      - name: Vale
        uses: errata-ai/vale-action@518a9136acc6e6668ce7c00d367051e0941e87ff # v3.0.0
        with:
          filter_mode: added
          debug: true
        env:
          # Required
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
